apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-app
spec:
  selector:
    matchLabels:
      app: apigateway-app
  replicas: 1
  template:
    metadata:
      labels:
        app: apigateway-app
    spec:
      containers:
      - name: apigateway-app
        image: rajalm/apigateway:0.0.1
        imagePullPolicy: Always
        ports:
          - containerPort: 9004
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway-svc
spec:
  selector:
    app: apigateway-app
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 9004

      