apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-ui-app
spec:
  selector:
    matchLabels:
      app: client-ui-app
  replicas: 1
  template:
    metadata:
      labels:
        app: client-ui-app
    spec:
      containers:
      - name: client-ui-app
        image: rajalm/client-ui
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: client-ui-svc
spec:
  selector:
    app: client-ui-app
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080

      