apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-app
spec:
  selector:
    matchLabels:
      app: config-server-app
  replicas: 1
  template:
    metadata:
      labels:
        app: config-server-app
    spec:
      containers:
      - name: config-server-app
        image: rajalm/config-server
        imagePullPolicy: Always
        ports:
          - containerPort: 9101
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-svc
spec:
  selector:
    app: config-server-app
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9101

      